import type { FeedMessage } from '@/types'
import { relativeTime } from '@/lib/time'

interface Props {
  message: FeedMessage
}

const dotColorMap = {
  alert: 'bg-error',
  manager: 'bg-maroon',
  info: 'bg-gray-dim',
}

// Feed senders that are software, not people. Machine-authored content always
// carries a visible accountability chain to a human (pattern from block/buzz
// MessageAgentOwner, Apache 2.0): an agent never appears autonomous.
const AGENT_SENDERS: Record<string, string> = {
  Briefing: 'Alejandro',
}

export function MessageCard({ message }: Props) {
  const managedBy = AGENT_SENDERS[message.senderName]
  return (
    <div className="bg-surface rounded-xl px-[18px] py-3.5">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className={`w-2 h-2 rounded-full ${dotColorMap[message.messageType]}`} />
          <span className="text-white text-sm font-semibold">{message.senderName}</span>
        </div>
        <span className="text-gray-dim text-[11px]">{relativeTime(message.timestamp)}</span>
      </div>

      {/* Body */}
      <p className="text-gray text-sm leading-relaxed mt-2 pl-4">
        {message.messageText}
      </p>

      {/* Agent authorship chip -- who answers for this message */}
      {managedBy && (
        <p className="mt-2 pl-4 text-gray-dim text-xs">
          <span className="inline-block rounded-full border border-gray-dim/40 px-2 py-0.5">
            automated -- managed by {managedBy}
          </span>
          <span className="sr-only">This message was generated by software managed by {managedBy}</span>
        </p>
      )}
    </div>
  )
}
